### Server Port Config ###
server:
  port: 10101
## Logback
logging:
  level:
    root: INFO
### SPRING Config ###
spring:
  application:
    name: ACCOUNT_IM
  main:
    allow-bean-definition-overriding: true
### Mybatis Config ###
  mybatis:
    config-location: classpath:mybatis-config.xml
### thymeleaf Config ###
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
### DataSource Config - IBM DB2 ###
  db2:
    datasource:
      hikari:
        pool-name: DB2-PRD
        driver-class-name: com.ibm.as400.access.AS400JDBCDriver
        jdbc-url: jdbc:as400://000.000.000.000;libraries=ACCOUNT_IM;date format=iso;
        username: user01
        password: user!1234  
### Spring JPA Config ###
  jpa:
    database: DB2
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show-sql: true
        format-sql: true  
        
### DataSource Config - IBM DB2 ###
  mssql:
    datasource:
      hikari:
        pool-name: MSSQL-PRD
        driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
        jdbc-url: jdbc:sqlserver://000.000.000.000:1433;databaseName=master;encrypt=false;trustServerCertificate=true;
        username: sa
        password: user!1234   